variables:
  GOBO: '$CI_PROJECT_DIR'

integration:
  stage: integration
  script:
    - Write-Host "Just to define the 'integration' stage name"
  except:
    refs:
      - tags
      - branches

install_windows:
  stage: integration
  tags:
    - shared-windows
    - windows
    - windows-1809
  script:
    - '& "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64'
    - '& "$env:CI_PROJECT_DIR\bin\install.bat" -v msc'

install_linux:
  stage: integration
  tags:
    - linux
  script:
    - $CI_PROJECT_DIR/bin/install.sh -v gcc

stages:
  - integration
