variables:
  GOBO: '$CI_PROJECT_DIR'

#
# Running tests with Gobo Eiffel.
#

test:
  stage: test_ge
  script:
    - Write-Host "Just to define the 'test_ge' stage name"
  rules:
    - when: never

test_library_windows:
  stage: test_ge
  tags:
    - shared-windows
    - windows
    - windows-1809
  script:
    - '& "$env:GOBO\.gitlab\do_it.bat" "$env:GOBO\bin\install.bat" -v msc'
    - '& "$env:GOBO\.gitlab\do_it.bat" gec --version'
    - cd "$env:GOBO\library"
    # The tests in `$GOBO\library\lexical` are failing in GitLab when using `geant test_ge`.
    - '& "$env:GOBO\.gitlab\do_it.bat" geant test_debug_ge'
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == null
      when: on_success

# We have `test_tool_no_gec_windows` and `test_tool_gec_windows`, instead
# of just `test_tool_windows`, because it takes more than 1 hour to run
# this job and the job timeout on GitLab runners for Windows is set to 1 hour
# (even though it is set to 2 hours for the project).

test_tool_no_gec_windows:
  stage: test_ge
  tags:
    - shared-windows
    - windows
    - windows-1809
  script:
    - '& "$env:GOBO\.gitlab\do_it.bat" "$env:GOBO\bin\install.bat" -v msc'
    - '& "$env:GOBO\.gitlab\do_it.bat" gec --version'
    - Remove-Item "$env:GOBO\tool\gec\test" -Force -Recurse
    - cd "$env:GOBO\tool"
    - '& "$env:GOBO\.gitlab\do_it.bat" geant test_ge'
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == null
      when: on_success

test_tool_gec_windows:
  stage: test_ge
  tags:
    - shared-windows
    - windows
    - windows-1809
  script:
    - '& "$env:GOBO\.gitlab\do_it.bat" "$env:GOBO\bin\install.bat" -v msc'
    - '& "$env:GOBO\.gitlab\do_it.bat" gec --version'
    - cd "$env:GOBO\tool\gec"
    - '& "$env:GOBO\.gitlab\do_it.bat" geant test_ge'
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == null
      when: on_success

test_library_linux:
  stage: test_ge
  tags:
    - linux
  script:
    - cat /etc/*-release
    - arch
    - gcc --version
    - $GOBO/bin/install.sh -v gcc
    - export PATH=$PATH:$GOBO/bin
    - gec --version
    - cd $GOBO/library
    - geant test_ge
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == null
      when: on_success

test_tool_linux:
  stage: test_ge
  tags:
    - linux
  script:
    - cat /etc/*-release
    - arch
    - gcc --version
    - $GOBO/bin/install.sh -v gcc
    - export PATH=$PATH:$GOBO/bin
    - gec --version
    - cd $GOBO/tool
    - geant test_ge
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == null
      when: on_success

#
# Running tests with ISE Eiffel.
#

test_ise:
  stage: test_ise
  script:
    - Write-Host "Just to define the 'test_ise' stage name"
  rules:
    - when: never

test_ise_library_argument_linux:
  stage: test_ise
  tags:
    - linux
  script:
    - cat /etc/*-release
    - arch
    - gcc --version
    - $GOBO/bin/install.sh -v gcc
    - export PATH=$PATH:$GOBO/bin
    - gec --version
    - source $GOBO/.gitlab/install_ise.sh
    - cd $GOBO/library
    - geant test_debug_ise
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $GOBO_CUSTOM_PIPELINE == "test_ise"
      when: on_success


#
# Stages.
#

stages:
  - test_ge
  - test_ise
