variables:
  GOBO: '$CI_PROJECT_DIR'

integration:
  stage: integration
  script:
    - Write-Host "Just to define the 'integration' stage name"
  except:
    refs:
      - tags
      - branches

install_windows:
  stage: integration
  tags:
    - windows
  script:
    - '& "$env:CI_PROJECT_DIR\bin\install.bat" -v gcc'

install_linux:
  stage: integration
  tags:
    - linux
  script:
    - "$CI_PROJECT_DIR/bin/install.sh" -v gcc

stages:
  - integration
