language: eiffel

# Use full virtual machine.
dist: trusty
sudo: required

branches:
  # Build all branches:
  only:
  - gh-pages
  - /.*/

before_script:
  # Install Gobo Eiffel
  - export GOBO=$PWD
  - travis_wait 60 bin/install.sh -v -t gcc
  - export PATH=$PATH:$GOBO/bin

env:
  matrix:
    - GOBO_TEST_DIR=library
    - GOBO_TEST_DIR=tool

script: 
  # Test
  - cd $GOBO/$GOBO_TEST_DIR
  - geant test_debug_ge
