language: c

# Use full virtual machine.
dist: xenial
sudo: required
  
branches:
  # Build all branches:
  only:
  - gh-pages
  - /.*/

os:
  - linux
  - osx

before_script:
  # Install Gobo Eiffel
  - export GOBO=$PWD
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_wait 60 bin/install.sh -v -t gcc; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then travis_wait 60 bin/install.sh -v -t clang; fi
  - export PATH=$PATH:$GOBO/bin
  - echo `gec --version`
  # Install ISE Eiffel (see https://www.eiffel.org/setup/)
  - cd $GOBO/..
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export ISE_PLATFORM=linux-x86-64; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export ISE_PLATFORM=macosx-x86-64; fi
  - curl -sSL https://www.eiffel.org/setup/install.sh | bash -s -- --url https://ftp.eiffel.com/pub/beta/nightly/Eiffel_20.05_rev_104521-$ISE_PLATFORM.tar.bz2 > eiffel.rc
  - source ./eiffel.rc
  # Make sure that we are using our version of the Gobo tools.
  - rm -rf $ISE_EIFFEL/library/gobo/spec
  - echo `ec -version`
  - cd $GOBO

env:
  - TRAVIS_GOBO_TEST_DIR=library TRAVIS_GOBO_EIFFEL=ge
  - TRAVIS_GOBO_TEST_DIR=tool TRAVIS_GOBO_EIFFEL=ge
  - TRAVIS_GOBO_TEST_DIR=library/argument TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/common TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/free_elks TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/kernel TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/lexical TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/math TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/parse TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/pattern TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/regexp TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/string TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/structure TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/test TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/thread TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/time TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/tools TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/utility TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/xml TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/xpath TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=library/xslt TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=tool/geant TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=tool/gec TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=tool/gecc TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=tool/gedoc TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=tool/gelex TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=tool/gelint TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=tool/gepp TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=tool/getest TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=tool/gexslt TRAVIS_GOBO_EIFFEL=ise
  - TRAVIS_GOBO_TEST_DIR=tool/geyacc TRAVIS_GOBO_EIFFEL=ise

matrix:
  exclude:
# Tests do not work for with ISE on MacOS because of incompatibilities in versions of libiconv.2.dylib.
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/argument TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/common TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/free_elks TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/kernel TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/lexical TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/math TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/parse TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/pattern TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/regexp TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/string TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/structure TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/test TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/thread TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/time TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/tools TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/utility TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/xml TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/xpath TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=library/xslt TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=tool/geant TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=tool/gec TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=tool/gecc TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=tool/gedoc TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=tool/gelex TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=tool/gelint TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=tool/gepp TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=tool/getest TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=tool/gexslt TRAVIS_GOBO_EIFFEL=ise
    - os: osx
      env: TRAVIS_GOBO_TEST_DIR=tool/geyacc TRAVIS_GOBO_EIFFEL=ise
  
script: 
  # Test
  - cd $GOBO/$TRAVIS_GOBO_TEST_DIR
  - travis_wait 60 geant test_debug_$TRAVIS_GOBO_EIFFEL
