language: eiffel

branches:
  # Build all branches:
  only:
  - gh-pages
  - /.*/

before_script:
  # Install Gobo Eiffel
  - export GOBO=$PWD
  - travis_wait 60 bin/install.sh -v -t gcc
  - export PATH=$PATH:$GOBO/bin

script: 
  # Testing
  - cd $GOBO/library/argument
  - geant test_debug_ge
  - cd $GOBO/library/common
  - geant test_debug_ge
  - cd $GOBO/library/free_elks
  - geant test_debug_ge
  - cd $GOBO/library/kernel
  - geant test_debug_ge
  - cd $GOBO/library/lexical
  - geant test_debug_ge
  - cd $GOBO/library/math
  - geant test_debug_ge
  - cd $GOBO/library/parse
  - geant test_debug_ge
  - cd $GOBO/library/pattern
  - geant test_debug_ge
  - cd $GOBO/library/regexp
  - geant test_debug_ge
  - cd $GOBO/library/string
  - geant test_debug_ge
  - cd $GOBO/library/structure
  - geant test_debug_ge
  - cd $GOBO/library/test
  - geant test_debug_ge
  - cd $GOBO/library/thread
  - geant test_debug_ge
  - cd $GOBO/library/time
  - geant test_debug_ge
  - cd $GOBO/library/tools
  - geant test_debug_ge
  - cd $GOBO/library/utility
  - geant test_debug_ge
  - cd $GOBO/library/xml
  - geant test_debug_ge
  - cd $GOBO/library/xpath
  - geant test_debug_ge
  - cd $GOBO/library/xslt
  - travis_wait 60 geant test_debug_ge
  - cd $GOBO/tool/geant
  - geant test_debug_ge
  #- cd $GOBO/tool/gec
  #- geant test_debug_ge
  - cd $GOBO/tool/gedoc
  - geant test_debug_ge
  - cd $GOBO/tool/gelex
  - geant test_debug_ge
  #- cd $GOBO/tool/gelint
  #- geant test_debug_ge
  - cd $GOBO/tool/gepp
  - geant test_debug_ge
  #- cd $GOBO/tool/getest
  #- geant test_debug_ge
  - cd $GOBO/tool/gexace
  - geant test_debug_ge
  #- cd $GOBO/tool/gexslt
  #- geant test_debug_ge
  - cd $GOBO/tool/geyacc
  - geant test_debug_ge
