language: c

# Use full virtual machine.
dist: xenial
sudo: required
  
branches:
  # Build all branches:
  only:
  - gh-pages
  - /.*/

os:
  - osx
  - linux

env:
  - GOBO_CI_SYSTEM_UNDER_TEST=library GOBO_CI_EIFFEL_COMPILER=ge
  - GOBO_CI_SYSTEM_UNDER_TEST=tool GOBO_CI_EIFFEL_COMPILER=ge
  
script:
  - source "$TRAVIS_BUILD_DIR/.cicd/build_ge.sh" travis
  - cd $GOBO/$GOBO_CI_SYSTEM_UNDER_TEST
  - travis_wait 60 geant test_${GOBO_CI_EIFFEL_COMPILER}
