language: eiffel

# Use full virtual machine.
dist: trusty
sudo: required

branches:
  # Build all branches:
  only:
  - gh-pages
  - /.*/

env:
  matrix:
    - GOBO_TEST_DIR=library
    - GOBO_TEST_DIR=tool

jobs:
  include:
    - stage: Gobo Eiffel
      script:
        - export GOBO=$PWD
        # Install Gobo Eiffel
        - travis_wait 60 bin/install.sh -v -t gcc
        - export PATH=$PATH:$GOBO/bin
        # Test
        - cd $GOBO/$GOBO_TEST_DIR
        - geant test_debug_ge
