language: c

# Use full virtual machine.
dist: xenial
sudo: required

branches:
  # Build all branches:
  only:
  - gh-pages
  - /.*/

os:
  - linux
  - osx

before_script:
  # Install Gobo Eiffel
  - export GOBO=$PWD
  - travis_wait 60 bin/install.sh -v -t gcc
  - export PATH=$PATH:$GOBO/bin
  - echo `gec --version`
  # Install ISE Eiffel
  - cd $GOBO/..
  - export TRAVIS_ISE_VERSION=18.07
  - export TRAVIS_ISE_SUB_VERSION=101981
  - export ISE_EIFFEL=$PWD/Eiffel_$TRAVIS_ISE_VERSION
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export ISE_PLATFORM=linux-x86-64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export ISE_PLATFORM=macosx-x86-64; fi
  - curl -sSL https://ftp.eiffel.com/pub/download/$TRAVIS_ISE_VERSION/Eiffel_${TRAVIS_ISE_VERSION}_gpl_${TRAVIS_ISE_SUB_VERSION}-$ISE_PLATFORM.tar.bz2 | tar -x --bzip2
  - export PATH=$PATH:$ISE_EIFFEL/studio/spec/$ISE_PLATFORM/bin:$PATH:$ISE_EIFFEL/tools/spec/$ISE_PLATFORM/bin
  - echo `ec -version`
  - cd $GOBO

env:
  matrix:
    - TRAVIS_GOBO_TEST_DIR=library TRAVIS_GOBO_EIFFEL=ge
    - TRAVIS_GOBO_TEST_DIR=tool TRAVIS_GOBO_EIFFEL=ge
    - TRAVIS_GOBO_TEST_DIR=library TRAVIS_GOBO_EIFFEL=ise
    - TRAVIS_GOBO_TEST_DIR=tool TRAVIS_GOBO_EIFFEL=ise

script: 
  # Test
  - cd $GOBO/$TRAVIS_GOBO_TEST_DIR
  - travis_wait 60 geant test_debug_$TRAVIS_GOBO_EIFFEL
