stages:

#
# Build Gobo tools.
#

  - template: .azure/build.yml
    parameters:
      os: linux
      vm_image: ubuntu-latest

  - template: .azure/build.yml
    parameters:
      os: macos
      vm_image: macos-latest

  - template: .azure/build.yml
    parameters:
      os: windows
      vm_image: windows-latest

#
# Running tests.
#

  - template: .azure/test.yml
    parameters:
      os: linux
      vm_image: ubuntu-latest

  - template: .azure/test.yml
    parameters:
      os: macos
      vm_image: macos-latest

  - template: .azure/test.yml
    parameters:
      os: windows
      vm_image: windows-latest
