name: Continuous Integration

jobs:

#
# Build Gobo tools.
#

  - job: linux_build
    pool:
      vmImage: ubuntu-latest
    steps:
      - pwsh: . "$(Build.Repository.LocalPath)/.cicd/build_ge.ps1" azure
        name: build
      - publish: $(Build.Repository.LocalPath)/bin
        artifact: gobo_bin_linux
      - publish: $(Build.Repository.LocalPath)/tool/gec/config/c/default.cfg
        artifact: gobo_c_config_linux

  - job: macos_build
    pool:
      vmImage: macos-latest
    steps:
      - pwsh: . "$(Build.Repository.LocalPath)/.cicd/build_ge.ps1" azure
        name: build
      - publish: $(Build.Repository.LocalPath)/bin
        artifact: gobo_bin_macos
      - publish: $(Build.Repository.LocalPath)/tool/gec/config/c/default.cfg
        artifact: gobo_c_config_macos

  - job: windows_build
    pool:
      vmImage: windows-latest
    steps:
      - pwsh: . "$(Build.Repository.LocalPath)/.cicd/build_ge.ps1" azure
        name: build
      - publish: $(Build.Repository.LocalPath)/bin
        artifact: gobo_bin_windows
      - publish: $(Build.Repository.LocalPath)/tool/gec/config/c/default.cfg
        artifact: gobo_c_config_windows
