#
# Build Gobo tools.
#

parameters:
  os: ''
  vm_image: ''

stages:
  - stage: ${{ parameters.os }}_build
    jobs:
      - job: ${{ parameters.os }}_build
        pool:
          vmImage: ${{ parameters.vm_image }}
        steps:
          - pwsh: . "$(Build.Repository.LocalPath)/.cicd/build_ge.ps1" azure
            name: build
          - publish: "$(Build.Repository.LocalPath)/bin"
            artifact: gobo_bin_${{ parameters.os }}
          - publish: "$(Build.Repository.LocalPath)/tool/gec/config/c/default.cfg"
            artifact: gobo_c_config_${{ parameters.os }}
