#
# Running tests.
#

parameters:
  os: ''
  vm_image: ''

stages:
  - stage: ${{ parameters.os }}_test
    dependsOn: ${{ parameters.os }}_build
    jobs:
      - job: ${{ parameters.os }}_test
        pool:
          vmImage: ${{ parameters.vm_image }}
        strategy:
          matrix:
            ge_library:
              GOBO_CI_EIFFEL_COMPILER: ge
              GOBO_CI_SYSTEM_UNDER_TEST: library
            ge_tool:
              GOBO_CI_EIFFEL_COMPILER: ge
              GOBO_CI_SYSTEM_UNDER_TEST: tool
        steps:
          - download: current
            artifact: gobo_bin_${{ parameters.os }}
          - pwsh: Move-Item -Path "$(Pipeline.Workspace)/gobo_bin_${{ parameters.os }}/*" -Destination "$(Build.Repository.LocalPath)/bin" -Force
          - download: current
            artifact: gobo_c_config_${{ parameters.os }}
          - pwsh: Move-Item -Path "$(Pipeline.Workspace)/gobo_c_config_${{ parameters.os }}/*" -Destination "$(Build.Repository.LocalPath)/tool/gec/config/c" -Force
          - pwsh: . "$(Build.Repository.LocalPath)/.cicd/test_ge.ps1" azure $env:GOBO_CI_EIFFEL_COMPILER $env:GOBO_CI_SYSTEM_UNDER_TEST
            name: test
