name: Continuous Integration

on: [push, pull_request]

jobs:

#
# Build Gobo tools.
#

  linux_build:
    runs-on: ubuntu-latest
    strategy:
    steps:
      - uses: actions/checkout@v2
      - name: before_script
        run: source .github/before_script.sh
      - name: build
        run: source .github/build_ge.sh
      - uses: actions/upload-artifact@v2
        with:
          name: gobo_bin_linux
          path: bin
          retention-days: 1
      - uses: actions/upload-artifact@v2
        with:
          name: gobo_c_config_linux
          path: tool/gec/config/c/default.cfg
          retention-days: 1

  macos_build:
    runs-on: macos-latest
    strategy:
    steps:
      - uses: actions/checkout@v2
      - name: before_script
        run: source .github/before_script.sh
      - name: build
        run: source .github/build_ge.sh
      - uses: actions/upload-artifact@v2
        with:
          name: gobo_bin_macos
          path: bin
          retention-days: 1
      - uses: actions/upload-artifact@v2
        with:
          name: gobo_c_config_macos
          path: tool/gec/config/c/default.cfg
          retention-days: 1

#
# Running tests.
#

  linux_test:
    runs-on: ubuntu-latest
    needs: linux_build
    strategy:
      matrix:
        eiffel_compiler: [ge, debug_ise]
        system_under_test: [library, tool]
    steps:
      - uses: actions/checkout@v2
      - name: before_script
        run: source .github/before_script.sh
      - uses: actions/download-artifact@v2
        with:
          name: gobo_bin_linux
          path: bin
      - uses: actions/download-artifact@v2
        with:
          name: gobo_c_config_linux
          path: tool/gec/config/c
      - name: test
        run: |
          source .github/install_ge.sh
          if [ ${{ matrix.eiffel_compiler }} = "debug_ise" ]; then
            source $GOBO/.github/install_ise.sh
          fi
          cd $GOBO/${{ matrix.system_under_test }}
          geant test_${{ matrix.eiffel_compiler }}

  macos_test:
    runs-on: macos-latest
    needs: macos_build
    strategy:
      matrix:
        eiffel_compiler: [ge, debug_ise]
        system_under_test: [library, tool]
    steps:
      - uses: actions/checkout@v2
      - name: before_script
        run: source .github/before_script.sh
      - uses: actions/download-artifact@v2
        with:
          name: gobo_bin_macos
          path: bin
      - uses: actions/download-artifact@v2
        with:
          name: gobo_c_config_macos
          path: tool/gec/config/c
      - name: test
        run: |
          source .github/install_ge.sh
          if [ ${{ matrix.eiffel_compiler }} = "debug_ise" ]; then
            source $GOBO/.github/install_ise.sh
          fi
          cd $GOBO/${{ matrix.system_under_test }}
          geant test_${{ matrix.eiffel_compiler }}
