name: Continuous Integration

on: [push, pull_request]

jobs:

#
# Build Gobo tools.
#

  linux_ge_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: before_script
        run: source $GOBO/.github/before_script.sh
      - uses: actions/checkout@v2
      - name: build
        run: source $GOBO/.github/build_ge.sh
      - uses: actions/upload-artifact@v2
        with:
          name: gobo_bin_$RUNNER_OS
          path: bin
          retention-days: 1
      - uses: actions/upload-artifact@v2
        with:
          name: gobo_c_config_$RUNNER_OS
          path: tool/gec/config/c/default.cfg
          retention-days: 1

#
# Running tests with Gobo Eiffel.
#

  linux_ge_test_library:
    runs-on: ubuntu-latest
    needs: linux_ge_build
    steps:
      - name: before_script
        run: source $GOBO/.github/before_script.sh
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: gobo_bin_$RUNNER_OS
          path: bin
      - uses: actions/download-artifact@v2
        with:
          name: gobo_c_config_$RUNNER_OS
          path: tool/gec/config/c
      - name: test
        run: |
          source $GOBO/.github/install_ge.sh
          cd $GOBO/library
          geant test_ge

  linux_ge_test_tool:
    runs-on: ubuntu-latest
    needs: linux_ge_build
    steps:
      - name: before_script
        run: source $GOBO/.github/before_script.sh
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: gobo_bin_$RUNNER_OS
          path: bin
      - uses: actions/download-artifact@v2
        with:
          name: gobo_c_config_$RUNNER_OS
          path: tool/gec/config/c
      - name: test
        run: |
          source $GOBO/.github/install_ge.sh
          cd $GOBO/tool
          geant test_ge

#
# Running tests with ISE Eiffel.
#

  linux_ise_test_library:
    runs-on: ubuntu-latest
    needs: linux_ge_build
    steps:
      - name: before_script
        run: source $GOBO/.github/before_script.sh
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: gobo_bin_$RUNNER_OS
          path: bin
      - uses: actions/download-artifact@v2
        with:
          name: gobo_c_config_$RUNNER_OS
          path: tool/gec/config/c
      - name: test
        run: |
          source $GOBO/.github/install_ge.sh
          source $GOBO/.github/install_ise.sh
          cd $GOBO/library
          geant test_debug_ise

  linux_ise_test_tool:
    runs-on: ubuntu-latest
    needs: linux_ge_build
    steps:
      - name: before_script
        run: source $GOBO/.github/before_script.sh
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: gobo_bin_$RUNNER_OS
          path: bin
      - uses: actions/download-artifact@v2
        with:
          name: gobo_c_config_$RUNNER_OS
          path: tool/gec/config/c
      - name: test
        run: |
          source $GOBO/.github/install_ge.sh
          source $GOBO/.github/install_ise.sh
          cd $GOBO/tool
          geant test_debug_ise
