name: "GitHub Actions"

on: [push, pull_request]

jobs:

#
# Build Gobo tools.
#

  linux_gcc_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: . "$env:GITHUB_WORKSPACE/.cicd/build_ge.ps1" github gcc
        shell: pwsh
      - uses: actions/upload-artifact@v3
        with:
          name: gobo_bin_linux_gcc
          path: bin
          retention-days: 1
      - uses: actions/upload-artifact@v3
        with:
          name: gobo_c_config_linux_gcc
          path: tool/gec/backend/c/config/default.cfg
          retention-days: 1

  macos_clang_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: . "$env:GITHUB_WORKSPACE/.cicd/build_ge.ps1" github clang
        shell: pwsh
      - uses: actions/upload-artifact@v3
        with:
          name: gobo_bin_macos_clang
          path: bin
          retention-days: 1
      - uses: actions/upload-artifact@v3
        with:
          name: gobo_c_config_macos_clang
          path: tool/gec/backend/c/config/default.cfg
          retention-days: 1

  windows_msc_build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: . "$env:GITHUB_WORKSPACE/.cicd/build_ge.ps1" github msc
      - uses: actions/upload-artifact@v3
        with:
          name: gobo_bin_windows_msc
          path: bin
          retention-days: 1
      - uses: actions/upload-artifact@v3
        with:
          name: gobo_c_config_windows_msc
          path: tool/gec/backend/c/config/default.cfg
          retention-days: 1

#
# Running tests.
#
  
  linux_gcc_test:
    runs-on: ubuntu-latest
    needs: linux_gcc_build
    strategy:
      fail-fast: false
      matrix:
        eiffel_compiler: [ge, debug_ge, ise, debug_ise]
        system_under_test: [library, tool]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: gobo_bin_linux_gcc
          path: bin
      - uses: actions/download-artifact@v3
        with:
          name: gobo_c_config_linux_gcc
          path: tool/gec/backend/c/config
      - name: test
        run: . "$env:GITHUB_WORKSPACE/.cicd/test_ge.ps1" github gcc ${{ matrix.eiffel_compiler }} ${{ matrix.system_under_test }}
        shell: pwsh

  macos_clang_test:
    runs-on: macos-latest
    needs: macos_clang_build
    strategy:
      fail-fast: false
      matrix:
        eiffel_compiler: [ge, debug_ge, ise, debug_ise]
        system_under_test: [library, tool]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: gobo_bin_macos_clang
          path: bin
      - uses: actions/download-artifact@v3
        with:
          name: gobo_c_config_macos_clang
          path: tool/gec/backend/c/config
      - name: test
        run: . "$env:GITHUB_WORKSPACE/.cicd/test_ge.ps1" github clang ${{ matrix.eiffel_compiler }} ${{ matrix.system_under_test }}
        shell: pwsh

  windows_msc_test:
    runs-on: windows-latest
    needs: windows_msc_build
    strategy:
      fail-fast: false
      matrix:
        eiffel_compiler: [ge, debug_ge, ise, debug_ise]
        system_under_test: [library, tool]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: gobo_bin_windows_msc
          path: bin
      - uses: actions/download-artifact@v3
        with:
          name: gobo_c_config_windows_msc
          path: tool/gec/backend/c/config
      - name: test
        run: . "$env:GITHUB_WORKSPACE/.cicd/test_ge.ps1" github msc ${{ matrix.eiffel_compiler }} ${{ matrix.system_under_test }}
